=== University-of-Potsdam-MM/motivate-rulegenerator/resources/ContextInformation.dtd
<!ELEMENT contextInformation (information)*>
<!ELEMENT information (contextClasses?,contextValue,parameters?)>
<!ATTLIST information 
	id ID #REQUIRED
	multiplicity (UNIQUE|MULTIPLE) "UNIQUE">
<!ELEMENT contextClasses (contextClass)*>
<!ELEMENT contextClass EMPTY>
<!ATTLIST contextClass id (CC_TECHNICAL|CC_PHYSICAL|CC_PERSONAL|CC_SITUATIONAL|CC_SCENARIO|CC_LOCATION) #REQUIRED>
<!ELEMENT contextValue (operators,possibleValues?)>
<!ATTLIST contextValue 
	type (STRING|FLOAT|INTEGER|BOOLEAN|ENUM) #REQUIRED
	min CDATA #IMPLIED
	max CDATA #IMPLIED
	default CDATA #IMPLIED>
<!ELEMENT operators (operator)+>
<!ELEMENT operator EMPTY>
<!ATTLIST operator id (GREATER_THEN|LESS_THEN|IS|IS_NOT|CONTAINS|NO_VALUE) #REQUIRED>
<!ELEMENT parameters (parameter)+>
<!ELEMENT parameter (parameterValue)>
<!ATTLIST parameter id CDATA #REQUIRED>
<!ELEMENT parameterValue (possibleValues?)>
<!ATTLIST parameterValue 
	type (STRING|FLOAT|INTEGER|BOOLEAN|ENUM) #REQUIRED
	min CDATA #IMPLIED
	max CDATA #IMPLIED
	default CDATA #IMPLIED>
<!ELEMENT possibleValues (value)+>
<!ELEMENT value (#PCDATA)>

=== University-of-Potsdam-MM/motivate-rulegenerator/measurable-context-information.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contextInformation SYSTEM "ContextInformation.dtd">
<contextInformation>
	<!-- Context information for the default rule generation assembly. -->
	<information id="CI_CURRENT_LEARNING_UNIT">
		<contextClasses>
			<contextClass id="CC_SCENARIO" />
		</contextClasses>
		<contextValue type="STRING">
			<operators>
				<operator id="CONTAINS" />
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="NO_VALUE" />
			</operators>
		</contextValue>
	</information>
	<information id="CI_FINISHED_LEARNING_UNIT" multiplicity="MULTIPLE">
		<contextClasses>
			<contextClass id="CC_SCENARIO" />
		</contextClasses>
		<contextValue type="STRING">
			<operators>
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="NO_VALUE" />
			</operators>
		</contextValue>
	</information>
	<!-- End -->
	<!-- Context information that covers actions performed by the user. -->
	<information id="CI_USER_DID_PERFORM_ACTION" multiplicity="MULTIPLE">
		<contextClasses>
			<contextClass id="CC_PERSONAL" />
			<contextClass id="CC_SITUATIONAL" />
		</contextClasses>
		<contextValue type="ENUM">
			<operators>
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="CONTAINS" />
			</operators>
			<possibleValues>
				<value>ACTIVATE_ACTION</value>
				<value>CHOOSE_ACTION</value>
				<value>DEACTIVATE_ACTION</value>
				<value>RESUME_ACTION</value>
				<value>SUSPEND_ACTION</value>
				<value>WATCH_ACTION</value>
				<value>VIEW_ACTION</value>
				<value>USE_ACTION</value>
				<value>LISTEN_ACTION</value>
				<value>READ_ACTION</value>
			</possibleValues>
		</contextValue>
		<parameters>
			<parameter id="CP_ACTION_START_TIMESTAMP">
				<parameterValue type="INTEGER" />
			</parameter>
			<parameter id="CP_ACTION_END_TIMESTAMP">
				<parameterValue type="INTEGER" />
			</parameter>
			<parameter id="CP_ACTION_REFERNCED_LEARNING_NUGGET">
				<parameterValue type="STRING" />
			</parameter>
		</parameters>
	</information>
	<!-- End -->
	<information id="CI_AUDIO_OUTPUT_AVAILABLE">
		<contextClasses>
			<contextClass id="CC_TECHNICAL" />
		</contextClasses>
		<contextValue type="BOOLEAN">
			<operators>
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="NO_VALUE" />
			</operators>
		</contextValue>
	</information>
	<information id="CI_CURRENT_AIR_PRESSURE">
		<contextClasses>
			<contextClass id="CC_PHYSICAL" />
		</contextClasses>
		<contextValue type="FLOAT">
			<operators>
				<operator id="GREATER_THEN" />
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="LESS_THEN" />
				<operator id="NO_VALUE" />
			</operators>
		</contextValue>
		<parameters>
			<parameter id="CP_PRESSURE_UNIT">
				<parameterValue type="ENUM">
					<possibleValues>
						<value>BAR</value>
						<value>MILLIMETER_OF_MERCURY</value>
						<value>PASCAL</value>
						<value>TORR</value>
					</possibleValues>
				</parameterValue>
			</parameter>
		</parameters>
	</information>
	<information id="CI_CURRENT_AMBIENT_NOISE">
		<contextClasses>
			<contextClass id="CC_PHYSICAL" />
		</contextClasses>
		<contextValue type="FLOAT">
			<operators>
				<operator id="GREATER_THEN" />
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="LESS_THEN" />
				<operator id="NO_VALUE" />
			</operators>
		</contextValue>
	</information>
	<information id="CI_CURRENT_APPOINTMENT">
		<contextClasses>
			<contextClass id="CC_SITUATIONAL" />
		</contextClasses>
		<contextValue type="STRING">
			<operators>
				<operator id="CONTAINS" />
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="NO_VALUE" />
			</operators>
		</contextValue>
		<parameters>
			<parameter id="CP_APPOINTMENT_DETAIL">
				<parameterValue type="ENUM">
					<possibleValues>
						<value>DATE</value>
						<value>LOCATION</value>
						<value>NOTES</value>
						<value>TIME</value>
						<value>TITLE</value>
					</possibleValues>
				</parameterValue>
			</parameter>
		</parameters>
	</information>
	<information id="CI_CURRENT_HUMIDITY">
		<contextClasses>
			<contextClass id="CC_PHYSICAL" />
		</contextClasses>
		<contextValue type="FLOAT">
			<operators>
				<operator id="GREATER_THEN" />
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="LESS_THEN" />
				<operator id="NO_VALUE" />
			</operators>
		</contextValue>
	</information>
	<information id="CI_CURRENT_LUMINOSITY">
		<contextClasses>
			<contextClass id="CC_PHYSICAL" />
		</contextClasses>
		<contextValue type="FLOAT">
			<operators>
				<operator id="GREATER_THEN" />
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="LESS_THEN" />
				<operator id="NO_VALUE" />
			</operators>
		</contextValue>
	</information>
	<information id="CI_CURRENTLY_RAINING">
		<contextClasses>
			<contextClass id="CC_PHYSICAL" />
		</contextClasses>
		<contextValue type="BOOLEAN">
			<operators>
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="NO_VALUE" />
			</operators>
		</contextValue>
	</information>
	<information id="CI_CURRENTLY_SUNNY">
		<contextClasses>
			<contextClass id="CC_PHYSICAL" />
		</contextClasses>
		<contextValue type="BOOLEAN">
			<operators>
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="NO_VALUE" />
			</operators>
		</contextValue>
	</information>
	<information id="CI_CURRENT_TEMPERATURE">
		<contextClasses>
			<contextClass id="CC_PHYSICAL" />
		</contextClasses>
		<contextValue type="FLOAT">
			<operators>
				<operator id="GREATER_THEN" />
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="LESS_THEN" />
				<operator id="NO_VALUE" />
			</operators>
		</contextValue>
		<parameters>
			<parameter id="CP_TEMPERATURE_SCALE">
				<parameterValue type="ENUM">
					<possibleValues>
						<value>CELSIUS</value>
						<value>FAHRENHEIT</value>
						<value>KELVIN</value>
					</possibleValues>
				</parameterValue>
			</parameter>
		</parameters>
	</information>
	<information id="CI_CURRENT_TIME">
		<contextClasses>
			<contextClass id="CC_PHYSICAL" />
		</contextClasses>
		<contextValue type="INTEGER">
			<operators>
				<operator id="GREATER_THEN" />
				<operator id="LESS_THEN" />
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="NO_VALUE" />
			</operators>
		</contextValue>
		<parameters>
			<parameter id="CP_TIME_COMPONENT">
				<parameterValue type="ENUM">
					<possibleValues>
						<value>HOURS</value>
						<value>MINUTES</value>
						<value>SECONDS</value>
					</possibleValues>
				</parameterValue>
			</parameter>
		</parameters>
	</information>
	<information id="CI_DEVICE_TYPE">
		<contextClasses>
			<contextClass id="CC_TECHNICAL" />
		</contextClasses>
		<contextValue type="ENUM">
			<operators>
				<operator id="CONTAINS" />
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="NO_VALUE" />
			</operators>
			<possibleValues>
				<value>FEATURE_PHONE</value>
				<value>TABLET_COMPUTER</value>
				<value>SMARTPHONE</value>
				<value>SMARTWATCH</value>
				<value></value>
			</possibleValues>
		</contextValue>
	</information>
	<information id="CI_DISPLAY_RESOLUTION">
		<contextClasses>
			<contextClass id="CC_TECHNICAL" />
		</contextClasses>
		<contextValue type="INTEGER">
			<operators>
				<operator id="GREATER_THEN" />
				<operator id="LESS_THEN" />
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="NO_VALUE" />
			</operators>
		</contextValue>
		<parameters>
			<parameter id="CP_RESOLUTION_COMPONENT">
				<parameterValue type="ENUM">
					<possibleValues>
						<value>WIDTH</value>
						<value>HEIGHT</value>
					</possibleValues>
				</parameterValue>
			</parameter>
			<parameter id="CP_RESOLUTION_UNIT">
				<parameterValue type="ENUM">
					<possibleValues>
						<value>PIXELS</value>
						<value>POINTS</value>
						<value>CENTIMETERS</value>
					</possibleValues>
				</parameterValue>
			</parameter>
		</parameters>
	</information>
	<information id="CI_EXPECTED_TIME_NEEDED_FOR_COMPLETION">
		<contextClasses>
			<contextClass id="CC_SCENARIO" />
		</contextClasses>
		<contextValue type="INTEGER">
			<operators>
				<operator id="GREATER_THEN" />
				<operator id="LESS_THEN" />
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="NO_VALUE" />
			</operators>
		</contextValue>
		<parameters>
			<parameter id="CP_LEARNING_UNIT_ID">
				<parameterValue type="STRING" />
			</parameter>
		</parameters>
	</information>
	<information id="CI_EXTERNAL_DISPLAY_AVAILABLE">
		<contextClasses>
			<contextClass id="CC_TECHNICAL" />
		</contextClasses>
		<contextValue type="BOOLEAN">
			<operators>
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="NO_VALUE" />
			</operators>
		</contextValue>
	</information>
	<information id="CI_HAS_SCREEN_READER_FUNCTIONALITY">
		<contextClasses>
			<contextClass id="CC_TECHNICAL" />
		</contextClasses>
		<contextValue type="BOOLEAN">
			<operators>
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="NO_VALUE" />
			</operators>
		</contextValue>
	</information>
	<information id="CI_MICROPHONE_AVAILABLE">
		<contextClasses>
			<contextClass id="CC_TECHNICAL" />
		</contextClasses>
		<contextValue type="BOOLEAN">
			<operators>
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="NO_VALUE" />
			</operators>
		</contextValue>
	</information>
	<information id="CI_NEXT_APPOINTMENT">
		<contextClasses>
			<contextClass id="CC_SITUATIONAL" />
		</contextClasses>
		<contextValue type="STRING">
			<operators>
				<operator id="CONTAINS" />
				<operator id="IS" />
				<operator id="IS_NOT" />
				<operator id="NO_VALUE" />
			</operators>
		</contextValue>
		<parameters>
			<parameter id="CP_APPOINTMENT_DETAIL">
				<parameterValue type="ENUM">
					<possibleValues>
						<value>DATE</value>
						<value>LOCATION</value>
						<value>NOTES</value>
						<value>TIME</value>
						<value>TITLE</value>
